### ISSUE TITLE
Doesn't start up on Windows 10

### ISSUE THREAD

**Issue by derkrasseleo** [studiorack/studiorack-app#1]
- The App won't run under Windows 10 Pro 21H1.
- I tried reinstalling and running as admin.
- When I look at my Task Manager, I can see many (12) processes called "StudioRack" running in the background but nothing really happens.

Is there any way to troubleshoot this or can I look at some log files?

**Comment by kmturley** [comment]
Thanks for checking it out. The app is in beta at the moment and I haven't tested it on Windows yet.
I'm in the middle of re-writing the core libraries which the app depends on so quite a bit changing!
Will get back to you soon with an update!

**Comment by derkrasseleo** [comment]
I see, I will come back later then. I will close this issue for now.

**Comment by kmturley** [comment]
Just tested on Windows 10 Home and the app didn't run.

Installation steps went fine
![Screenshot 2021-04-14 214431](https://user-images.githubusercontent.com/1710493/114815987-29e78680-9d6c-11eb-8fb3-d2fb6eb1c96e.png)

Icon appear on desktop is not correct icon
![Screenshot 2021-04-14 214505](https://user-images.githubusercontent.com/1710493/114816042-3f5cb080-9d6c-11eb-8251-862901959f94.png)

Task manager shows multiple processes but no window
![Screenshot 2021-04-14 214842](https://user-images.githubusercontent.com/1710493/114816092-500d2680-9d6c-11eb-9711-1f1bdb65eb31.png)

When I run the dev version locally I get the error:
`(node:10548) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setIcon' of undefined`

Looks like the dock is only available on MacOS. Have added an if statement around it and the app is now working again:

![Screenshot 2021-04-14 220944](https://user-images.githubusercontent.com/1710493/114817090-41277380-9d6e-11eb-8011-ef96c779eda2.png)

This is still an Alpha version of the App, changing lots of things right now!
