### ISSUE TITLE
develop a roadmap of development and how you plan on increasing adoption

### ISSUE THREAD

**Issue by RustoMCSpit** [studiorack/studiorack-app#14]

**Comment by kmturley** [comment]
Yes agree this would be a good idea.
Adding to enhancements

**Comment by RustoMCSpit** [comment]
add it to readme. this should be the first of the issues addressed in my eyes. you can make something like this https://github.com/users/scottcorgan/projects/1

**Comment by kmturley** [comment]
I have projects to track:

- Plugin suggestions: https://github.com/orgs/studiorack/projects/2
- Feature suggestions: https://github.com/orgs/studiorack/projects/3
- Issues: https://github.com/orgs/studiorack/projects/5

They are public and allow anyone to see my roadmap and planned features!

**Comment by RustoMCSpit** [comment]
> I have projects to track:
> 
> * Plugin suggestions: https://github.com/orgs/studiorack/projects/2
> * Feature suggestions: https://github.com/orgs/studiorack/projects/3
> * Issues: https://github.com/orgs/studiorack/projects/5
> 
> They are public and allow anyone to see my roadmap and planned features!

thank you so much, you do so fucking much man ❤
