### ISSUE TITLE
Appimage not working

### ISSUE THREAD

**Issue by UltraBlackLinux** [studiorack/studiorack-app#2]
Hey there,
I just tried running the appimage and I even tried using `npm run pack-app` but there is a problem: The window is just white (`(node:36424) electron: Failed to load URL: file:///home/maus/Downloads/studiorack-app-main/dist/linux-unpacked/resources/app.asar/renderer/out/projects.html with error: ERR_FILE_NOT_FOUND`)
I have no clue why this is, but the app works fine with `npm run start` , so it seems like a file is lost when creating the binary.
Please fix this!
Thanks!

**Comment by kmturley** [comment]
Hello,
Thanks for trying out the app. I don't have a Linux machine, so it is the least tested of the Operating Systems, there are likely bugs!

I have just tested using:

- Virtual Box v6.1 (https://www.virtualbox.org/)
- Ubuntu Desktop v20.04.3 (https://ubuntu.com/download/desktop)

After that I downloaded and install the dependencies using the commands:
```
sudo apt install git
sudo snap install node --classic --channel 17/stable
mkdir ./Sites && cd ./Sites
git clone https://github.com/studiorack/studiorack-app.git
cd studiorack-app
npm install
npm run dev
```

The app loads just fine in dev mode:
![VirtualBox_Ubuntu_03_01_2022_21_36_13](https://user-images.githubusercontent.com/1710493/148014681-40d56001-9e23-4f2a-afe1-20cf274a5284.png)

If I build the final binary using:
```
npm run dist
```
(This is how the release binaries are created in the GitHub pipeline code here):
https://github.com/studiorack/studiorack-app/blob/main/.github/workflows/release.yml#L50

I do see an error:
![VirtualBox_Ubuntu_03_01_2022_21_53_50](https://user-images.githubusercontent.com/1710493/148015496-ffc6190d-7998-4e88-97aa-d380f002fde5.png)

Thanks for reporting, will investigate!

**Comment by kmturley** [comment]
I have found the issue. When I switched the app to use to server-side rendering, NextJS still tried to export the the pages as static content.

But the original template had the export command for static content:
```
"build-renderer": "next build renderer && next export renderer",
```
https://github.com/vercel/next.js/blob/canary/examples/with-electron-typescript/package.json#L8

I removed the package.json commands to this:
```
"build-renderer": "next build renderer",
```
https://github.com/studiorack/studiorack-app/blob/main/package.json#L11

But now the static content is not generated (including icons)
If I replace the origin command the build fails because NextJS is trying to export the pages as static content, but they are not.

I will need to refactor the code to fix this issue. Will let you know when there is a fix

**Comment by kmturley** [comment]
This issue has now been fixed.
Please note the app is still in beta and is not fully stable/tested!

**Comment by UltraBlackLinux** [comment]
I'm having trouble still - At the moment I'm getting an internal server error, even though the website seems to be running fine...

The console is also pretty useless, just a "Clientside exception"

**Comment by kmturley** [comment]
Hmm you're right. If I run the AppImage built on Linux it works:
<img width="1488" alt="Screen Shot 2022-03-03 at 8 03 32 PM" src="https://user-images.githubusercontent.com/1710493/156697481-2b858f50-845c-435c-9302-5426d35fdde2.png">

However If I download the build from the GitHub CI Pipeline it doesn't work:
<img width="1487" alt="Screen Shot 2022-03-03 at 8 04 35 PM" src="https://user-images.githubusercontent.com/1710493/156697534-ac01c850-0370-48b7-9961-8d947c7e0dab.png">

Investigating...

**Comment by kmturley** [comment]
Added debug code to catch the runtime error:
https://stackoverflow.com/a/70638485/2068766

Revealed this error:
```
> Ready on http://localhost:3000
+ /tmp/.mount_studiorYTHOn/resources/app.asar/node_modules/@studiorack/core/dist/config.json
Error: ENOENT, node_modules/@studiorack/core/dist/config.json not found in /tmp/.mount_studiorYTHOn/resources/app.asar
    at createError (node:electron/js2c/asar_bundle:5:1243)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1962)
    at Object.writeFileSync (node:fs:2143:35)
    at fileCreate (/tmp/.mount_studiorYTHOn/resources/app.asar/node_modules/@studiorack/core/dist/file.js:136:25)
    at Object.fileJsonCreate (/tmp/.mount_studiorYTHOn/resources/app.asar/node_modules/@studiorack/core/dist/file.js:160:12)
    at configSet (/tmp/.mount_studiorYTHOn/resources/app.asar/node_modules/@studiorack/core/dist/config.js:20:12)
    at getServerSideProps (/tmp/.mount_studiorYTHOn/resources/app.asar/renderer/.next/server/pages/projects.js:191:64)
    at Object.renderToHTML (/tmp/.mount_studiorYTHOn/resources/app.asar/node_modules/next/dist/server/render.js:589:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async doRender (/tmp/.mount_studiorYTHOn/resources/app.asar/node_modules/next/dist/server/base-server.js:879:38) {
  errno: -2
}
```

However when running a linux built AppImage it works with:
```
> Ready on http://localhost:3000
+ /tmp/.mount_studiocSZNnG/resources/app.asar/node_modules/@studiorack/core/dist/config.json
⌕ /home/kim/**/*.{als,cpr,flp,logic,ptx,rpp}
```

Paths are identical in both builds:
```
/tmp/.mount_studiorYTHOn/resources/app.asar/node_modules/@studiorack/core/dist/config.json
/tmp/.mount_studiocSZNnG/resources/app.asar/node_modules/@studiorack/core/dist/config.json
```

One build must be including the files and another one missing them. The build from the GitHub pieline is also smaller, indicating there could be missing files:
<img width="1250" alt="Screen Shot 2022-03-03 at 9 01 49 PM" src="https://user-images.githubusercontent.com/1710493/156702494-d9cb922f-56c0-499f-81ea-1b0eee47ec3f.png">

Investigating further...

**Comment by kmturley** [comment]
I believe it's permissions issues. I get similar issues when trying to install plugins in the mac build:
```
node:electron/js2c/renderer_init:65 Uncaught (in promise) Error: Error invoking remote method 'pluginInstall': Error: ENOENT: no such file or directory, mkdir './temp/ryukau/vstplugins/cubic-pad-synth'
    at EventEmitter.i.invoke (node:electron/js2c/renderer_init:65)
```

When you build the binary on the same machine as it is being run, it must have permission.
When the binary is built on another machine (GitHub pipeline) the code is not trusted and has permissions issues.

I will need to spend time testing the permissions for all platforms. and take a look through the security recommendations here:
https://www.electronjs.org/docs/latest/tutorial/security

**Comment by UltraBlackLinux** [comment]
> I believe it's permissions issues. I get similar issues when trying to install plugins in the mac build:
> 
> ```
> node:electron/js2c/renderer_init:65 Uncaught (in promise) Error: Error invoking remote method 'pluginInstall': Error: ENOENT: no such file or directory, mkdir './temp/ryukau/vstplugins/cubic-pad-synth'
>     at EventEmitter.i.invoke (node:electron/js2c/renderer_init:65)
> ```
> 
> When you build the binary on the same machine as it is being run, it must have permission. When the binary is built on another machine (GitHub pipeline) the code is not trusted and has permissions issues.
> 
> I will need to spend time testing the permissions for all platforms. and take a look through the security recommendations here: https://www.electronjs.org/docs/latest/tutorial/security

There usually shouldn't be any permission problems - The files should all have the owner and group 1000 (it's like the default user afaik), but Github CI never messed those things up for me

EDIT: Unless it's an electron specific thing, the file permissions in the appimage are correct - I extracted it, changed the perms to the correct ones, repacked it and it's still broken...

EDIT 2: I tried to build the appimage myself to see if the problem persists, but I can't for the life of me get the build process to finish (https://github.com/electron-userland/electron-builder/issues/6456)

**Comment by kmturley** [comment]
I spent some time investigating and found a few potential issues which required changes:

1) Upgrading to latest Electron
https://github.com/studiorack/studiorack-app/commit/6953632f949ce4ef5e04dc8ae818348c9ef9059d

2) Rewrote the Web -> Electron communication to follow security best-practices
Use new contextBridge and enable contextIsolation for security
https://github.com/studiorack/studiorack-app/commit/9b68a1ec82b8af965a737cf3de0051d5ac909226

3) Cross-platform appData directory and paths
https://github.com/studiorack/studiorack-core/commit/d087306d9f16d55d5b15c5f1b081bed7b93e3dd6

Testing the latest build in Ubuntu it seems item 3) was preventing the config from loading. Either the location of the config.json or the way I was joining paths with slashes.

The latest build is running, and navigable. However when installing a plugin there is still an error:
```
(in promise) Error: Error invoking remote method 'pluginInstall': Error: EACCES: permission denied, mkdir '/usr/local/lib/VST3/ryukau/vstplugins/colliding-comb-synth/0.1.1'
```

Will continue to investigate this issue

**Comment by kmturley** [comment]
It appears that the Electron process by default does not have permissions to write files outside of the user AppData directory.

Potential solutions:
1. Instruct user to run StudioRack Electron app with elevated privileges (e.g. Admin)
2. Wrap Electron app in https://www.npmjs.com/package/electron-sudo which will prompt user to enter Admin password, then run StudioRack as child process after password is entered.
3. Run only the plugin install step as child process with elevated privileges (prompt the first time for password)

My worry is that running the entire Electron app with elevated privileges would be a security risk. Also dangerous if there was a bug, imagine wiping all your files on your machine.

I was sure there must be someone who has done this before. Looking at open-source Electron apps which also write files to System directories... I realized! https://github.com/microsoft/vscode

In the [package.json](https://github.com/microsoft/vscode/blob/main/package.json) file they have two interesting dependencies:

- https://www.npmjs.com/package/native-is-elevated
- https://www.npmjs.com/package/@vscode/sudo-prompt

They check to see if permissions are elevated using `native-is-elevated`, and if not prompt for an admin password using `sudo-prompt`.

Looking at the logic is interesting. They only use the elevated permissions to copy a file from temp folder to a system directory. I guess this is for security.
https://github.com/microsoft/vscode/blob/8845f89c1e4183b54126cd629cd45c8f0f7549f2/src/vs/platform/native/electron-main/nativeHostMainService.ts#L491

Will look into a coded solution for StudioRack soon.

**Comment by kmturley** [comment]
I've successfully replicated the VSCode logic as a separate minimal example app:
https://github.com/kmturley/electron-runas-admin

Everything seems to work as expected. Next step is to integrated this code into StudioRack.
My planned approach is everytime a plugin is installed it will:

1. Download the plugin .zip file from GitHub Releases into a temp folder
2. Extract the .zip into a temp folder
3. Trigger Runas Admin step which will prompt user for their admin password
4. Copy the files from temp folder to Plugin directory.

Will take a look at this work in the coming week

**Comment by ThePinkUnicorn6** [comment]
Using the download from github on windows 10 gives me the same issue, is there any update on a fix?

**Comment by kmturley** [comment]
@ThePinkUnicorn6 Thanks for trying out StudioRack!

The app is still in beta and there are still a few issue to work out. This is my first Electron app so there have been a few bumps! I am currently the only contributor to this project and working on it in my spare time, so progress has been slow.

I have been making updates to the core package which shares the logic for installing/uninstalling plugins:
https://github.com/studiorack/studiorack-core/commits/main

I am currently working on triggering an Admin prompt when plugins are installed into a System directory. This work is almost complete and there will be a new beta release soon.

In the meantime you can use the website or the command line to search and install plugins!

**Comment by kmturley** [comment]
I managed to trigger Admin prompts and then install plugins with elevated privileges. The installation process is a little slow, but something that I can optimize over time.

I have publish beta v0.0.27 which should be fixed for Mac and Linux:
https://github.com/studiorack/studiorack-app/releases/tag/v0.0.27

Below are screenshots of the StudioRack app installing plugins successfully for each platform.

MacOS Monterey 12.2.1
<img width="1075" alt="Screen Shot 2022-04-06 at 9 12 56 PM" src="https://user-images.githubusercontent.com/1710493/162121408-57149b3f-891d-4a2d-82b3-64fd5f03a987.png">

Linux (VirtualBox Ubuntu)
<img width="1061" alt="Screen Shot 2022-04-06 at 7 16 58 PM" src="https://user-images.githubusercontent.com/1710493/162121376-1b0fcd5a-5f71-49c3-9ebb-a8f7488656a9.png">

Windows (VirtualBox Windows 10) not working
<img width="865" alt="Screen Shot 2022-04-06 at 9 50 03 PM" src="https://user-images.githubusercontent.com/1710493/162122379-57025bec-c20f-46a3-9329-05776373e940.png">

I will look into the Windows build next.

**Comment by UltraBlackLinux** [comment]
This admin problem leads me to believe that it also installs the plugins to the system - If so, why not just download it into the downloads directory or only install it to the user? How can that require root access?

**Comment by kmturley** [comment]
@UltraBlackLinux I have configured the default plugin installation directory to match Steinberg's recommendations:

- MacOS: `/Users/$USERNAME/Library/Audio/Plug-ins`
- Linux: `/usr/local/lib`
- Windows: `/Program Files/Common Files`

https://developer.steinberg.help/display/VST/Plug-in+Locations

However you can change the default directory in the app settings screen:

<img width="1113" alt="Screen Shot 2022-04-08 at 8 54 59 PM" src="https://user-images.githubusercontent.com/1710493/162555489-d6d03ae0-881b-4cf2-b8bb-4d8008060467.png">

I believe these directories require admin permissions to install files. In the future I am planning to only ask for admin permission if the installation directory is outside the App Data directory.

Closing this issue as it has been resolved on Linux/Mac. There is a separate issue for Windows which I will address here:
https://github.com/studiorack/studiorack-app/issues/3
