### ISSUE TITLE
500 Internale Server Error

### ISSUE THREAD

**Issue by CharlesBT** [studiorack/studiorack-app#3]
Hi, your StudioRack project looks very promising :).

I downloaded v0.0.27 win version from : https://github.com/studiorack/studiorack-app/releases/tag/v0.0.27
Granted access to windows firewall at launching the first time then I get this nasty error, looks like something is broken on szerver side

Charles

![Capture](https://user-images.githubusercontent.com/90343307/162427954-06bee01d-59e5-455b-9caf-b57133651b32.PNG)

**Comment by kmturley** [comment]
@CharlesBT Thanks for trying out the StudioRack app. It is currently in beta, and I haven't done much cross-platform testing so far, so there are quite a few bugs.

I ran the app from the GitHub source code on a VirtualBox Windows image. When running in dev mode you can see the errors in more detail.

The default projectFolder is set to C:\Users\abc, but when StudioRack scans this folder it gets permissions errors for sub directories.

<img width="1396" alt="Screen Shot 2022-04-08 at 9 53 23 PM" src="https://user-images.githubusercontent.com/1710493/162557167-14cd342f-92d0-4adb-b7a8-b12d3d4c1dd0.png">

<img width="704" alt="Screen Shot 2022-04-08 at 9 52 55 PM" src="https://user-images.githubusercontent.com/1710493/162557156-527985b9-3983-431e-8113-ddb6d41c6094.png">


One quick workaround is to open the config file at:
`C:\Users\abc\AppData\Roaming\studiorack\config.json`

Then update the `projectFolder` value to point to a single folder, and this will allow the UI to load (although empty!)

<img width="1376" alt="Screen Shot 2022-04-08 at 9 57 24 PM" src="https://user-images.githubusercontent.com/1710493/162557189-220ec102-48f1-4dab-a8dd-27e23ed8539a.png">

I will work on updating the default directory so this error does to occur. There are further errors in the Windows version of this app which I will need to fix.

It's a work-in-progress and there is only myself working on it currently!

**Comment by kmturley** [comment]
I've pushed a v0.0.28 with an updated default `pluginFolder` path for Windows:
https://github.com/studiorack/studiorack-app/releases/tag/v0.0.28

While running the source code on Windows I noticed there are issues with some of the methods returning the wrong values. Results are different on Windows than on Mac.

I modified my core library test pipeline to run on Linux, Mac and Windows:
https://github.com/studiorack/studiorack-core/actions

There are a few failures, I need to update those methods to ensure they are consistent cross-platform. Will respond here with another update when that work has been completed!

**Comment by kmturley** [comment]
@CharlesBT this should be fixed with the latest build. Will close.
Please reopen if you experience the issue again

**Comment by CharlesBT** [comment]
> @CharlesBT this should be fixed with the latest build. Will close. Please reopen if you experience the issue again

@kmturley I'd just tryied but same issue with v0.0.28

**Comment by kmturley** [comment]
@CharlesBT I've spent the past month updating the core library code to run/test complete on Windows
The updated latest release should fix all issues reported v.0.0.34
