### ISSUE TITLE
Download shouldn't be the same as installed

### ISSUE THREAD

**Issue by derkrasseleo** [studiorack/studiorack-app#5]
studiorack v.0.0.29 / windows 11

Some plugins seem to only download but don't get placed in the plugin folder. But the GUI says the plugin is installed.

![image](https://user-images.githubusercontent.com/16163571/163704634-b97fbeb0-2db7-4e2a-985c-a51227283786.png)

**Comment by kmturley** [comment]
Plugin installs fine on Mac. The Windows binary may have been zipped wrongly.

I have re-compressed and uploaded to the release:
https://github.com/studiorack/diopser/releases/tag/v0.0.1

Let me know if that fixes the issue?

**Comment by derkrasseleo** [comment]
#7 and #6 are blocking me from trying

**Comment by kmturley** [comment]
Can you try again since the latest releases?

**Comment by derkrasseleo** [comment]
Besides the plugin begin installed in the default path and not the one I set like I explained in #10 installing works fine. Uninstalling still doesn't work, see #7 

edit: Oh wait, now I restarted, and it says "install" but the plugin is still installed

**Comment by kmturley** [comment]
Thanks for your patience on this.

After testing on a Windows machine, I realized many of the core methods just didn't work.

I have spent the last week or so updating the core library test suite to run on Linux, Mac and Windows. Also to ensure all tests pass. Today I reached that milestone with this version:
https://github.com/studiorack/studiorack-core/actions/runs/2343366381

Now I need to update the core library in the CLI and app and test their functionality end-to-end.

Making progress!

**Comment by kmturley** [comment]
I have tested the new core library in the cli and app in Windows.
All works well for me, so you should be unblocked.

One thing to note, there are a few plugins which need their .exe installers unpacked. Currently if you install these plugins on Windows it will leave the .exe file in the download folder.

<img width="258" alt="Screen Shot 2022-05-29 at 2 49 40 PM" src="https://user-images.githubusercontent.com/1710493/170892645-75d3a235-1f36-40f0-b3fb-bd84c1f1e8ec.png">

**Comment by kmturley** [comment]
I have converted all .exe files to .zip so all plugins should now be compatible!
