### ISSUE TITLE
Plugin directory setting resets after restart

### ISSUE THREAD

**Issue by derkrasseleo** [studiorack/studiorack-app#6]
studiorack v.0.0.29 / windows 11
I tried setting the plugin directory to "Program Files/common Files", as this is the standard path, but after restarting, the setting changed back to "/Program Files (x86)/Common Files"

https://user-images.githubusercontent.com/16163571/163705488-998a3961-8c94-4858-bb2d-4921937cc2d4.mp4

Also, the cli doesn't seem to respect this setting..

![image](https://user-images.githubusercontent.com/16163571/163705032-0d46e07b-24b8-460c-b058-2ae74c460371.png)

And they apparently don't share the same config file..

![image](https://user-images.githubusercontent.com/16163571/163705556-f7918763-c8d5-46f3-982d-cecaa6e2518b.png)

Wait what??? I can set the path but when I get it, it doesn't get the actual path?!

![image](https://user-images.githubusercontent.com/16163571/163706041-f5ad8209-5fd8-4d94-a9be-c29a70c75f4c.png)

**Comment by kmturley** [comment]
Good catch, I replicated the issue. I don't know why but I wrote code which overwrote the settings on every load... I must've been tired.

This commit fixes the issue:
https://github.com/studiorack/studiorack-core/commit/80999ee2fe59ee9bd7042577fe101c5f053f2995

I will post an update again here when the core code has been built into an app release.

**Comment by derkrasseleo** [comment]
The issue was fixed with the release of version 0.0.30

**Comment by kmturley** [comment]
Thanks for proactively closing the ticket.

I am still testing Windows builds, for the other issue you opened. Everything works in dev mode but when the binary is created it breaks.

Still looking into the other issues!
