### ISSUE TITLE
Winget package

### ISSUE THREAD

**Issue by derkrasseleo** [studiorack/studiorack-app#8]
Just wanted to let you know, I submitted a winget package here: https://github.com/microsoft/winget-pkgs/pull/58967

This means, any Windows user can now install and update studiorack via CLI (winget). I don't know if there's a way to auto-update a package, but that would be a nice addition.

**Comment by kmturley** [comment]
Awesome, thanks for adding this.
I was going to look into distributing the app via package managers once it reaches a stable build.

I'm not familiar with `winget` but have used `choco` in my CICD pipelines to install dependencies:
https://github.com/studiorack/studiorack-workflows/search?q=choco

Any benefit to using one vs the other?

Electron has an auto-update feature, but I'm not experienced creating Electron apps and will leave that feature for a later date!

**Comment by derkrasseleo** [comment]
winget comes preinstalled on Windows (11), but I think you can install choco via winget, so it doesn't really matter. I wanted to try if studiorack would even work as a winget package and it seems like it does. One problem with self-updating apps is however, that they are stuck in an infinite upgrade loop, because winget checks the version of the installer (which often doesn't change) and tries to upgrade the app over and over again. But that is not an issue with studiorack right now so I would not go for self-upgrading.

**Comment by kmturley** [comment]
Sounds good, for now I presume this task is considered complete. Please reopen if you disagree!
